### ISSUE TITLE
MISP module requirement installation failed.

### ISSUE THREAD

**Issue by Merlain** [da667/AutoMISP#21]
Environment: Ubuntu 18.04.5 LTS (LXC image from Proxmox)

Error when installing https://github.com/MISP/misp-modules/blob/main/REQUIREMENTS 

```
Collecting opencv-python==4.4.0.44 (from -r REQUIREMENTS (line 56))

  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/38/a9/cd39fd25df434b5d9451dc266c12b72f68282a2b9bd5d7b4aa2d57d6c20e/opencv-python-4.4.0.44.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9w1zbvue/opencv-python/setup.py", line 9, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9w1zbvue/opencv-python/
```
solution : 
`pip3 install --upgrade pip`

```
Building wheels for collected packages: pydeep
  Building wheel for pydeep (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7bv28wzr/pydeep/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7bv28wzr/pydeep/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-g0i90ixd
       cwd: /tmp/pip-install-7bv28wzr/pydeep/
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'pydeep' extension
  creating build
  creating build/temp.linux-x86_64-3.6
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include/ -I/usr/include/python3.6m -c pydeep.c -o build/temp.linux-x86_64-3.6/pydeep.o
  pydeep.c:2:10: fatal error: fuzzy.h: No such file or directory
   #include <fuzzy.h>
            ^~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pydeep
  Running setup.py clean for pydeep
Failed to build pydeep
```

solution : 
`sudo apt-get install python-dev libfuzzy-dev`

**Comment by SteveClement** [comment]
There is an official installer that is well maintained and supported from Ubuntu 18.04 onwards, docs here: https://misp.github.io/MISP/INSTALL.ubuntu1804/

wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh
